---
# tasks file for ansible-role-haproxy
- name: Populate service facts
  service_facts:

- name: Install haproxy and socat packages.
  package:
    name: "{{ item }}"
    state: present
  register: package_res
  retries: 5
  until: package_res is success
  with_items:
    - haproxy
    - socat

- name: Enable and start the haproxy service
  service:
    name: haproxy
    state: started
    enabled: true

- name: Configure the haproxy cnf file with hosts
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Enable port {{ rh_demo_web_app_listen_port }} in firewalld
  firewalld:
    port: "{{ haproxy_frontend_port }}/tcp"
    permanent: yes
    immediate: true
    state: enabled
  when: "'firewalld.service' in services"
